/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionPlanRouteImport } from './routes/action-plan'
import { Route as AfterRouteImport } from './routes/after'
import { Route as BoundaryRouteImport } from './routes/boundary'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as HiddenLoadRouteImport } from './routes/hidden-load'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LabRouteImport } from './routes/lab'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlanRoute = ActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterRoute = AfterRouteImport.update({
  id: '/after',
  path: '/after',
  getParentRoute: () => rootRouteImport,
} as any)
const BoundaryRoute = BoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenLoadRoute = HiddenLoadRouteImport.update({
  id: '/hidden-load',
  path: '/hidden-load',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/after': typeof AfterRoute
  '/boundary': typeof BoundaryRoute
  '/check-in': typeof CheckInRoute
  '/hidden-load': typeof HiddenLoadRoute
  '/insights': typeof InsightsRoute
  '/lab': typeof LabRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/after': typeof AfterRoute
  '/boundary': typeof BoundaryRoute
  '/check-in': typeof CheckInRoute
  '/hidden-load': typeof HiddenLoadRoute
  '/insights': typeof InsightsRoute
  '/lab': typeof LabRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/after': typeof AfterRoute
  '/boundary': typeof BoundaryRoute
  '/check-in': typeof CheckInRoute
  '/hidden-load': typeof HiddenLoadRoute
  '/insights': typeof InsightsRoute
  '/lab': typeof LabRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-plan'
    | '/after'
    | '/boundary'
    | '/check-in'
    | '/hidden-load'
    | '/insights'
    | '/lab'
    | '/sandbox'
    | '/settings'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-plan'
    | '/after'
    | '/boundary'
    | '/check-in'
    | '/hidden-load'
    | '/insights'
    | '/lab'
    | '/sandbox'
    | '/settings'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/action-plan'
    | '/after'
    | '/boundary'
    | '/check-in'
    | '/hidden-load'
    | '/insights'
    | '/lab'
    | '/sandbox'
    | '/settings'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionPlanRoute: typeof ActionPlanRoute
  AfterRoute: typeof AfterRoute
  BoundaryRoute: typeof BoundaryRoute
  CheckInRoute: typeof CheckInRoute
  HiddenLoadRoute: typeof HiddenLoadRoute
  InsightsRoute: typeof InsightsRoute
  LabRoute: typeof LabRoute
  SandboxRoute: typeof SandboxRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plan': {
      id: '/action-plan'
      path: '/action-plan'
      fullPath: '/action-plan'
      preLoaderRoute: typeof ActionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after': {
      id: '/after'
      path: '/after'
      fullPath: '/after'
      preLoaderRoute: typeof AfterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boundary': {
      id: '/boundary'
      path: '/boundary'
      fullPath: '/boundary'
      preLoaderRoute: typeof BoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-load': {
      id: '/hidden-load'
      path: '/hidden-load'
      fullPath: '/hidden-load'
      preLoaderRoute: typeof HiddenLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionPlanRoute: ActionPlanRoute,
  AfterRoute: AfterRoute,
  BoundaryRoute: BoundaryRoute,
  CheckInRoute: CheckInRoute,
  HiddenLoadRoute: HiddenLoadRoute,
  InsightsRoute: InsightsRoute,
  LabRoute: LabRoute,
  SandboxRoute: SandboxRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
